[package]
name = "revm-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3.6", features = ["full"] }
anyhow = "1.0.89"
dotenv = "0.15.0"
revm = { version = "14.0.2", features = ["alloydb"] }
